### ISSUE TITLE
Removing self energies / calculating neighborlist in parallel

### ISSUE THREAD

**Issue by wiederm** [choderalab/modelforge#151]
The neighbor list and self energy calculations are currently done in sequence for each data point. As it is now the calculation takes around 40 minutes for the ANI2x dataset (the largest dataset in our collection right now). While this doesn't have high priority (it is a one time cost), I think we can parallalize this calculation using the PyTorch multiprocessing library with low additional efforts.

**Comment by chrisiacovella** [comment]
I think we can improve on this without going down the "traditional" parallel route. 

In the current approach, we lop over the conformers and calculate the pairs, one conformer at a time.  Once we get this pair info for a conformer, we basically just append this to a list that at the end is used to generate a large tensor (with a second tensor that tells us how to index into it for a given conformer). 

Since we are just creating a single large tensor at the end, we should be able to just do this all at once (or in manageable batch sizes), we just need to slightly modify the revised code I put in issue #141 and end up in PR #146.   that bit of code was just a modification of the original algorithm, but instead of creating two  n*(n-1) tensors for each batch and then eliminating pairs that are not on the same molecule, this code generates of those tensors takes into account the size of each conformer, so we never generate pairs with other molecules. If we simply change this to remove the offsetting (keeping each pair at 0-index basis), this will generate all the appropriate pairs.  Since the number of pairs per conformer something we can analytically compute based on number of atoms, we can also generate the appropriate indexing tensor. 

Doing it this way should speed things up because it will be one (or a few) large vector operations, rather than many small ones.

**Comment by wiederm** [comment]
I think this has been addressed in PR #161
