### ISSUE TITLE
Add data class for toml files

### ISSUE THREAD

**Issue by chrisiacovella** [choderalab/modelforge#200]
Currently .toml files are read into dictionaries.  To improve upon this, let us load these into a data class (more specifically use pydantic to create a data model).   I think it makes sense that this data class will actually be 4 separate data classes ( dataset,, potential, training, runtime) to match the breakdown in the .toml files (and allow us to maintain that hierarchy of what goes with what).

**Comment by wiederm** [comment]
that's a great idea!

Some thoughts on this: 
I would guess that at least every model needs its own dataclass. It seems difficult to come up with a superset of  all possible parameters for the potentials. A possible benefit of a superset would be that we can standardize naming conventions for the potentials.

I think the runtime toml file should only be used to override values set in one of the other toml files (a possible scenario where something like that is useful is when you have a single property that should differ between otherwise similar training runs, instead of defining a number of toml files that differ only in a single entire, we define a number of runtime toml files that include only the property that is different). Following from that use case I'd suggest that there shouldn't be a runtime dataclass (since it is only used to override fields).

**Comment by wiederm** [comment]
I think it would be super useful to provide a useful serialization of the dataclass for logging purpose. It might be as simple as converting the fully initialized dataclass to a dictionary and `pretty_print`

**Comment by wiederm** [comment]
Alternatively, runtime could also purely contain the entries that don't impact the training but the interaction with hardware and storage. That would mean the runtime.toml includes:
```
[runtime]
nr_of_epochs = 500
accelerator = "gpu"
num_nodes = 1
devices = 1                  #[0,1,2,3]
local_cache_dir = "./cache"
save_dir = "only_energy"
experiment_name = "{model_name}_{dataset_name}"
```

**Comment by chrisiacovella** [comment]
I'll note, that initially I was implementing default values into the pydantic models.  Based on discussion today, we do not want them in there, so that there is no possibility for ambiguity.  If a parameter is necessary and not defined, the code will fail.   

For some functions it don't think it would hurt to have a default, parameters, e.g., like a logging frequency, as that should not impact code function, but probably better to not include that for consistency. 

There are a few parameters that likely do not need to be defined for training to work.  For example  "early stopping" and "stochastic weight averaging" for sure can be optional.   The learning rate scheduling also likely could be optional as well.

**Comment by chrisiacovella** [comment]
I'll post a separate issue, but I think we'll want to do a major overhaul of the user facing functions to accept the pydantic models directly (possibly in place of standard pythonic variables) as a means to better dictate/validate inputs.
