### ISSUE TITLE
Issue generating angular_species12 tensor in ani2x

### ISSUE THREAD

**Issue by chrisiacovella** [choderalab/modelforge#96]
When I tried to train with the ani2x dataset  with ani2 nnp,  I ran into an issue of indices out of bounds (max bounds should be 6, given there are maximum of 7 atom types).  The translation from original atomic number down to 0 to n_max_atomtypes, seems to be not correct.    This didn't show up trying qm9 with ani2 nnp, because the there are only 5 atom types (max was default to 7).

**Comment by chrisiacovella** [comment]
I think I've tracked this down to  potential.utils.py  (line 135):

```
ATOMIC_NUMBER_TO_INDEX_MAP = {
    1: 0,  # H
    6: 1,  # C
    7: 2,  # N
    8: 3,  # O
    9: 4,  # F
    15: 5,  # P
    16: 6,  # S
    17: 7,  # Cl
    35: 8,  # Br
    53: 9,  # I
}
```

Since the ani nnp has only 7 atoms (H,C,N,O,F, S, Cl), we end up with the numbers being off by one because of "P" in this list.  The reason qm9 worked is that we only  had H, C, N, O, F so we never indexed more than the max number of atom types. 

If I hardcode in this dict into the ani.py model it will train (i.e., just leaving out P, Br, and I):

```
ATOMIC_NUMBER_TO_INDEX_MAP = {
            1: 0,  # H
            6: 1,  # C
            7: 2,  # N
            8: 3,  # O
            9: 4,  # F
            16: 5,  # S
            17: 6,  # Cl
        }
```

So I think we need to think about how to redo this to be flexible.  If we want to use ani with an arbitrary dataset (which many have more atomic species in it), we need to be able to adjust this dict, adjust max number of atomic species, and dynamically set up the atomic networks, i.e.:


```

        self.H_network = atomic_neural_networks["H"]
        self.C_network = atomic_neural_networks["C"]
        self.O_network = atomic_neural_networks["O"]
        self.N_network = atomic_neural_networks["N"]
        self.S_network = atomic_neural_networks["S"]
        self.F_network = atomic_neural_networks["F"]
        self.Cl_network = atomic_neural_networks["Cl"]
```

**Comment by wiederm** [comment]
Thanks for tracking this down @chrisiacovella !

The ANI architecture is unique. Each element-specific neural network only considers atoms with its specific element --- therefore adding a new element requires the careful construction of a balanced dataset. There is no 'transfer' learning like with other architectures (e.g., SchNet), in which each neural network layer is trained on each atom, and the element information is passed with the environment representation through the network. 
 
ANI-2x has been developed for a specific set of elements (H, C, O, N, S, F, and Cl), and we shouldn't add additional elements using the ANI-2x naming (the only difference between ANI-1x and ANI-2x is the number of elements). Since each new element adds a new multilayer perception, the number of parameters that need to be trained increases significantly. 

Having said all of this, I think it is worth adding a Phosphorus atomic network, and we might want to think about an element embedding instead of element-specific neural networks. But we can't call this ANI-2x.

**Comment by chrisiacovella** [comment]
Note, this issue has been fixed for now.  I think we need to discuss better how to handle this in a flexible way.  I'll create a new issue for that, since it will be an improvement, not a bug.
